### ISSUE TITLE
NPM install dies on 3.8 kernel for BBB

### ISSUE THREAD

**Issue by ril3y** [victorporof/BeagleBone-SPI-UART#3]
Do you have any specifics on what kernel version / BBB image is needed to use this to enable SPI?  I used `bone-debian-7.9-lxde-4gb-armhf-2015-11-12-4gb.img` from a fresh install and I get a ton of errors.

Thanks!

**Comment by victorporof** [comment]
Gosh, I don't remember... I know it was an up to date kernel about two years ago.

**Comment by ril3y** [comment]
I got it working with 3.8 funny I dont remember what I did to get it working.  However thanks for the lib.  Check it out I used it in our project for Shmoocon this year.

http://hackaday.com/2016/01/17/the-best-conference-booth-youll-ever-see/

**Comment by victorporof** [comment]
Nice!
